name: Typecheck

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download code onto Ubuntu machine
        uses: actions/checkout@v4

      - name: Install node.js 
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: Install dependencies
        run: npm install 

      - name: Run typescript compiler
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx
